image : mcr.microsoft.com/dotnet/sdk:latest
stages:
  - deploy
Deploy-Job:
  stage: deploy
  script:
    - npm install
    - npm install express
    - ($env:CI = "true") -and (npm run build)
    - $date = get-date -format  "dd-MM-yyyy"
    - mkdir -p "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Import-Module WebAdministration
    - Set-ItemProperty IIS:\Sites\kahkeshan -name physicalPath -value "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Copy-item -Force -Recurse -Verbose "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui\*" -Destination  "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    #- Stop-WebSite "kahkeshan"
    - Start-WebSite "kahkeshan"
    - ([Environment]::SetEnvironmentVariable("AdminApiS", [int64]$Env:AdminApiS + 1, "Machine"))
  tags:
    - Test
  artifacts:
  rules:
    - if: $CI_COMMIT_BRANCH == "Develop"
stage-Job:
  stage: deploy
  script: 
    - npm install
    - npm install express
    - ($env:CI = "false") -and (npm run build)
    - $date = get-date -format  "dd-MM-yyyy"
    - mkdir -p "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Import-Module WebAdministration
    - Set-ItemProperty IIS:\Sites\kahkeshan -name physicalPath -value "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Copy-item -Force -Recurse "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui\.next" -Destination  "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Copy-item -Force -Recurse "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui\node_modules" -Destination  "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Copy-item -Force -Recurse "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui\server.js" -Destination  "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Copy-item -Force -Recurse "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui\web.config" -Destination  "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Copy-item -Force -Recurse "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui\public" -Destination  "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Copy-item -Force -Recurse "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui\.env" -Destination  "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Stop-WebSite "kahkeshan"
    - Start-WebSite "kahkeshan"
    - Stop-WebAppPool -Name "kahkeshan"
    - Start-Sleep -Seconds 10
    - Start-WebAppPool -Name "kahkeshan"
    - Remove-Item -Force -Recurse "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui\*"
    - Remove-Item -Force -Recurse "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui.tmp\*"

    - ([Environment]::SetEnvironmentVariable("AdminApiS", [int64]$Env:AdminApiS + 1, "Machine"))
#    - cd c:\scripts\Clubui\
#    - .\only4backup

  tags:
    - StageApp
  artifacts:
  rules:
    - if: $CI_COMMIT_BRANCH == "Stage" 

Production-Job01:
  stage: deploy
  script: 
    - npm install
    - npm run build
    - cd /etc/kahkeshan-ui/
    - mkdir "kahkeshan.$(date '+%Y-%m-%d.V%H%M%S')"
    - sudo ls | sudo  sort -r | sudo head -n 1 > 1
    - pm2 delete kahkeshan && pm2 save --force
    - pm2 list
    - sudo rm -rf /etc/kahkeshan-ui/*
    - sudo cp /home/gitlab-runner/builds/y4etTpBpL/0/ui/kahkeshan-ui/next.config.js /etc/kahkeshan-ui/$1
    - sudo cp -rf /home/gitlab-runner/builds/y4etTpBpL/0/ui/kahkeshan-ui/node_modules /etc/kahkeshan-ui/$1
    - sudo cp /home/gitlab-runner/builds/y4etTpBpL/0/ui/kahkeshan-ui/package.json /etc/kahkeshan-ui/$1
    - sudo cp -rf /home/gitlab-runner/builds/y4etTpBpL/0/ui/kahkeshan-ui/public /etc/kahkeshan-ui/$1
    - sudo cp -rf /home/gitlab-runner/builds/y4etTpBpL/0/ui/kahkeshan-ui/src /etc/kahkeshan-ui/$1
    - sudo cp /home/gitlab-runner/builds/y4etTpBpL/0/ui/kahkeshan-ui/tsconfig.json /etc/kahkeshan-ui/$1
    - sudo cp /home/gitlab-runner/builds/y4etTpBpL/0/ui/kahkeshan-ui/.env /etc/kahkeshan-ui/$1
    - sudo cp -rf /home/gitlab-runner/builds/y4etTpBpL/0/ui/kahkeshan-ui/.next /etc/kahkeshan-ui/$1
    - cd /etc/kahkeshan-ui/$1
    - pm2 start npm --name "kahkeshan" -- run preview & pm2 save --force
    - sudo systemctl restart nginx

  tags:
    - Runner-KahkeshanUI01
  artifacts:
  rules:
    - if: $CI_COMMIT_BRANCH == "Production"

