image : mcr.microsoft.com/dotnet/sdk:latest
stages:
  - deploy
Deploy-Job:
  stage: deploy
  script:
    - npm install
    - npm install express
    - ($env:CI = "false") -and (npm run build)
    - $date = get-date -format  "dd-MM-yyyy"
    - mkdir -p "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Import-Module WebAdministration
    - Set-ItemProperty IIS:\Sites\kahkeshan -name physicalPath -value "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Copy-item -Force -Recurse -Verbose "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui\*" -Destination  "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    #- Stop-WebSite "kahkeshan"
    - Start-WebSite "kahkeshan"
    - ([Environment]::SetEnvironmentVariable("AdminApiS", [int64]$Env:AdminApiS + 1, "Machine"))
  tags:
    - Test
  artifacts:
  rules:
    - if: $CI_COMMIT_BRANCH == "Develop"
stage-Job:
  stage: deploy
  script: 
    - npm install
    - npm install express
    - ($env:CI = "false") -and (npm run build)
    - $date = get-date -format  "dd-MM-yyyy"
    - mkdir -p "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Import-Module WebAdministration
    - Set-ItemProperty IIS:\Sites\kahkeshan -name physicalPath -value "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Copy-item -Force -Recurse "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui\.next" -Destination  "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Copy-item -Force -Recurse "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui\node_modules" -Destination  "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Copy-item -Force -Recurse "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui\server.js" -Destination  "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Copy-item -Force -Recurse "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui\web.config" -Destination  "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Copy-item -Force -Recurse "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui\public" -Destination  "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Copy-item -Force -Recurse "D:\GitLab-Runner\builds\t6tP4xAxA\0\ui\kahkeshan-ui\.env" -Destination  "D:\Stage\UI\kahkeshanUi\Versions\kahkeshanUi.$date.$Env:AdminApiS\"
    - Stop-WebSite "kahkeshan"
    - Start-WebSite "kahkeshan"
    - Stop-WebAppPool -Name "kahkeshan"
    - Start-WebAppPool -Name "kahkeshan"

    - ([Environment]::SetEnvironmentVariable("AdminApiS", [int64]$Env:AdminApiS + 1, "Machine"))
#    - cd c:\scripts\Clubui\
#    - .\only4backup

  tags:
    - StageApp
  artifacts:
  rules:
    - if: $CI_COMMIT_BRANCH == "Stage" 
