export enum DateAsMillisecond {
	Day = 864e5,
	Week = 6048e5,
	Month = 2592e6,
	Year = 31536e6,
}

export enum EModalID {
	loginModal,
	optionFilters,
	confirm,
	moveSymbolToWatchlist,
	logout,
	blackScholes,
	orderDetails,
	addSymbolToWatchlist,
	addNewOptionWatchlist,
	manageOptionWatchlistList,
	choiceBroker,
	choiceCollateral,
	forgetPassword,
	buySell,
	addSaturnTemplate,
	selectSymbolContracts,
	changeBroker,
	symbolInfoPanelSetting,
	deposit,
	withdrawal,
	freeze,
	optionSettlement,
	analyze,
	description,
	transactionsFilters,
	instantDepositReportsFilters,
	depositWithReceiptReportsFilters,
	withdrawalCashReportsFilters,
	changeBrokerReportsFilters,
	freezeUnfreezeReportsFilters,
	cashSettlementReportsFilters,
	physicalSettlementReportsFilters,
	ordersReportsFilters,
	tradesReportsFilters,
	createStrategy,
	acceptAgreement,
	manageColumns,
	marketState,
	marketView,
	best,
	userProgressBar,
	compareTransactionValue,
	optionContract,
	optionTradeValue,
	optionMarketProcess,
	individualAndLegal,
	priceChangeWatchlist,
	openPositionProcess,
	meetings,
	newAndOld,
	topBaseAssets,
	recentActivities,
	dueDates,
	strategyFilters,
	chooseGuaranteeMethod,
}
