export const initialSymbolInfoPanelGrid: ISymbolInfoPanelGrid[] = [
	{
		id: 'option_detail',
		// 328 > 468
		// 328 > 628
		height: 328,
		expand: true,
		hidden: false,
		isOption: true,
		i: 0,
	},
	{
		id: 'market_depth',
		height: 200,
		expand: true,
		hidden: false,
		isOption: true,
		i: 1,
	},
	{
		id: 'symbol_detail',
		// 328 > 808
		height: 328,
		expand: true,
		hidden: false,
		isOption: false,
		i: 2,
	},
	{
		id: 'base_symbol_contracts',
		height: 320,
		expand: true,
		hidden: false,
		isOption: false,
		i: 1,
	},
	{
		id: 'user_open_positions',
		height: 320,
		expand: true,
		hidden: false,
		isOption: false,
		i: 2,
	},
	{
		id: 'quotes',
		height: 277,
		expand: true,
		hidden: false,
		isOption: false,
		i: 3,
	},
	{
		id: 'chart',
		height: 320,
		expand: true,
		hidden: false,
		i: 4,
	},
	{
		id: 'individual_and_legal',
		height: 270,
		expand: true,
		hidden: false,
		i: 5,
	},
	{
		id: 'option_individual_and_legal',
		height: 196,
		expand: true,
		hidden: false,
		i: 5,
	},
	{
		id: 'same_sector_symbols',
		height: 400,
		expand: true,
		hidden: false,
		isOption: false,
		i: 6,
	},
	{
		id: 'supervisor_messages',
		height: 360,
		expand: true,
		hidden: false,
		isOption: false,
		i: 7,
	},
];

export const initialDashboardGrid: IDashboardGrid[] = [
	{ id: 'market_view', w: 2, h: 384, hidden: false, i: 0 },
	{ id: 'market_state', w: 1, h: 384, hidden: false, i: 1 },
	{ id: 'best', w: 2, h: 384, hidden: false, i: 2 },
	// { id: 'user_progress_bar', w: 1, h: 384, hidden: false, i: 3 },
	{ id: 'compare_transaction_value', w: 2, h: 384, hidden: false, i: 3 },
	{ id: 'option_contracts', w: 1, h: 384, hidden: false, i: 4 },
	{ id: 'option_trades_value', w: 2, h: 384, hidden: false, i: 5 },
	{ id: 'option_market_process', w: 1, h: 384, hidden: false, i: 6 },
	{ id: 'individual_and_legal', w: 1, h: 384, hidden: false, i: 7 },
	{ id: 'price_changes_watchlist', w: 1, h: 384, hidden: false, i: 8 },
	{ id: 'open_positions_process', w: 1, h: 384, hidden: false, i: 9 },
	// { id: 'meetings', w: 1, h: 384, hidden: false, i: 11 },
	{ id: 'new_and_old', w: 1, h: 384, hidden: false, i: 10 },
	{ id: 'custom', w: 1, h: 384, hidden: false, i: 11 },
	{ id: 'due_dates', w: 1, h: 384, hidden: false, i: 12 },
	{ id: 'top_base_assets', w: 1, h: 384, hidden: false, i: 13 },
	// { id: 'recent_activities', w: 1, h: 384, hidden: false, i: 15 },
];

export const initialDashboardGridState: Record<TDashboardSections, boolean> = {
	best: true,
	compare_transaction_value: true,
	custom: true,
	due_dates: true,
	individual_and_legal: true,
	market_state: true,
	market_view: true,
	meetings: true,
	new_and_old: true,
	open_positions_process: true,
	option_contracts: true,
	option_market_process: true,
	option_trades_value: true,
	price_changes_watchlist: true,
	recent_activities: true,
	top_base_assets: true,
	user_progress_bar: true,
};
