// ? CoveredCall
export const initialHiddenColumnsCoveredCall: Record<TCoveredCallColumns, boolean> = {
	baseSymbolTitle: false,
	baseLastTradedPrice: false,
	dueDays: false,
	symbolTitle: false,
	strikePrice: false,
	openPositionCount: false,
	tradePriceVarPreviousTradePercent: true,
	optionBestBuyLimitPrice: false,
	optionBestBuyLimitQuantity: false,
	optionBestSellLimitPrice: true,
	optionBestSellLimitQuantity: true,
	coveredCallBEP: false,
	maxProfitPercent: false,
	nonExpiredProfitPercent: false,
	inUseCapital: false,
	bestSellYTM: true,
	nonExpiredYTM: true,
	bepDifference: true,
	riskCoverage: false,
	tradeValue: true,
	baseTradeValue: true,
	baseTradeCount: true,
	baseTradeVolume: true,
	baseLastTradedDate: true,
	action: false,
	ytm: false,
};

export const initialColumnsCoveredCall: Array<IManageColumn<TCoveredCallColumns>> = [
	{
		id: 'baseSymbolTitle',
		title: 'نماد پایه',
		hidden: initialHiddenColumnsCoveredCall.baseSymbolTitle,
		tag: 'PanelDetail',
		disabled: true,
	},
	{
		id: 'baseLastTradedPrice',
		title: 'قیمت پایه',
		hidden: initialHiddenColumnsCoveredCall.baseLastTradedPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'dueDays',
		title: 'مانده تا سررسید',
		hidden: initialHiddenColumnsCoveredCall.dueDays,
		tag: 'PanelDetail',
	},
	{
		id: 'symbolTitle',
		title: 'کال',
		hidden: initialHiddenColumnsCoveredCall.symbolTitle,
		tag: 'PanelDetail',
	},
	{
		id: 'strikePrice',
		title: 'قیمت اعمال',
		hidden: initialHiddenColumnsCoveredCall.strikePrice,
		tag: 'PanelDetail',
	},
	{
		id: 'openPositionCount',
		title: 'موقعیت باز',
		hidden: initialHiddenColumnsCoveredCall.openPositionCount,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestBuyLimitPrice',
		title: 'بهترین خریدار',
		hidden: initialHiddenColumnsCoveredCall.optionBestBuyLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestBuyLimitQuantity',
		title: 'حجم سرخط خرید',
		hidden: initialHiddenColumnsCoveredCall.optionBestBuyLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestSellLimitPrice',
		title: 'بهترین فروشنده',
		hidden: initialHiddenColumnsCoveredCall.optionBestSellLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestSellLimitQuantity',
		title: 'حجم سرخط فروش',
		hidden: initialHiddenColumnsCoveredCall.optionBestSellLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'coveredCallBEP',
		title: 'سر به سر',
		hidden: initialHiddenColumnsCoveredCall.coveredCallBEP,
		tag: 'Computational',
	},
	{
		id: 'maxProfitPercent',
		title: 'حداکثر بازده',
		hidden: initialHiddenColumnsCoveredCall.maxProfitPercent,
		tag: 'Computational',
	},
	{
		id: 'nonExpiredProfitPercent',
		title: 'بازده عدم اعمال',
		hidden: initialHiddenColumnsCoveredCall.nonExpiredProfitPercent,
		tag: 'Computational',
		disabled: true,
	},
	{
		id: 'inUseCapital',
		title: 'سرمایه درگیر',
		hidden: initialHiddenColumnsCoveredCall.inUseCapital,
		tag: 'Computational',
	},
	{
		id: 'tradePriceVarPreviousTradePercent',
		title: 'قیمت نماد آپشن',
		hidden: initialHiddenColumnsCoveredCall.tradePriceVarPreviousTradePercent,
		tag: 'PanelDetail',
	},
	{
		id: 'bepDifference',
		title: 'اختلاف تا سر به سر',
		hidden: initialHiddenColumnsCoveredCall.bepDifference,
		tag: 'Computational',
	},
	{
		id: 'tradeValue',
		title: 'ارزش معاملات آپشن',
		hidden: initialHiddenColumnsCoveredCall.tradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeValue',
		title: 'ارزش معاملات سهم پایه',
		hidden: initialHiddenColumnsCoveredCall.baseTradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeCount',
		title: 'تعداد معاملات پایه',
		hidden: initialHiddenColumnsCoveredCall.baseTradeCount,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeVolume',
		title: 'حجم معاملات پایه',
		hidden: initialHiddenColumnsCoveredCall.baseTradeVolume,
		tag: 'PanelDetail',
	},
	{
		id: 'baseLastTradedDate',
		title: 'آخرین معامله پایه',
		hidden: initialHiddenColumnsCoveredCall.baseLastTradedDate,
		tag: 'PanelDetail',
	},
	{
		id: 'ytm',
		title: 'YTM (بازده موثر)',
		hidden: initialHiddenColumnsCoveredCall.ytm,
		tag: 'Computational',
	},
	{
		id: 'nonExpiredYTM',
		title: 'YTM (بازده موثر) عدم اعمال',
		hidden: initialHiddenColumnsCoveredCall.nonExpiredYTM,
		tag: 'Computational',
		disabled: true,
	},
	{
		id: 'riskCoverage',
		title: 'پوشش ریسک',
		hidden: initialHiddenColumnsCoveredCall.riskCoverage,
		tag: 'Computational',
	},
];

// ? BullCallSpread
export const initialHiddenColumnsBullCallSpread: Record<TBullCallSpreadColumns, boolean> = {
	baseSymbolTitle: false,
	baseTradePriceVarPreviousTradePercent: false,
	dueDays: false,
	lspSymbolTitle: false,
	lspStrikePrice: false,
	lspBestSellLimitPrice: false,
	lspBestSellLimitQuantity: false,
	lspBestBuyLimitPrice: true,
	lspBestBuyLimitQuantity: true,
	hspSymbolTitle: false,
	hspStrikePrice: false,
	hspBestBuyLimitPrice: false,
	hspBestBuyLimitQuantity: false,
	hspBestSellLimitPrice: true,
	hspBestSellLimitQuantity: true,
	lspOpenPositionCount: true,
	hspOpenPositionCount: true,
	lspPremiumPercent: true,
	hspPremiumPercent: true,
	bullCallSpreadBEP: false,
	maxProfitPercent: false,
	maxLoss: false,
	inUseCapital: true,
	lspTimeValue: true,
	hspTimeValue: true,
	lspIntrinsicValue: true,
	hspIntrinsicValue: true,
	lspTradeValue: true,
	hspTradeValue: true,
	baseTradeValue: true,
	baseTradeCount: true,
	baseTradeVolume: true,
	baseLastTradedDate: true,
	ytm: true,
	actions: false,
};

export const initialColumnsBullCallSpread: Array<IManageColumn<TBullCallSpreadColumns>> = [
	{
		id: 'baseSymbolTitle',
		title: 'نماد پایه',
		hidden: initialHiddenColumnsBullCallSpread.baseSymbolTitle,
		tag: 'PanelDetail',
		disabled: true,
	},
	{
		id: 'baseTradePriceVarPreviousTradePercent',
		title: 'قیمت پایه',
		hidden: initialHiddenColumnsBullCallSpread.baseTradePriceVarPreviousTradePercent,
		tag: 'PanelDetail',
	},
	{
		id: 'dueDays',
		title: 'مانده تا سررسید',
		hidden: initialHiddenColumnsBullCallSpread.dueDays,
		tag: 'PanelDetail',
	},
	{
		id: 'lspSymbolTitle',
		title: 'کال خرید',
		hidden: initialHiddenColumnsBullCallSpread.lspSymbolTitle,
		tag: 'PanelDetail',
	},
	{
		id: 'lspStrikePrice',
		title: 'قیمت اعمال کال خرید',
		hidden: initialHiddenColumnsBullCallSpread.lspStrikePrice,
		tag: 'PanelDetail',
	},
	{
		id: 'lspBestSellLimitPrice',
		title: 'بهترین فروشنده کال خرید',
		hidden: initialHiddenColumnsBullCallSpread.lspBestSellLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'lspBestSellLimitQuantity',
		title: 'حجم فروشنده کال خرید',
		hidden: initialHiddenColumnsBullCallSpread.lspBestSellLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'lspBestBuyLimitPrice',
		title: 'قیمت خریدار کال خرید',
		hidden: initialHiddenColumnsBullCallSpread.lspBestBuyLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'lspBestBuyLimitQuantity',
		title: 'حجم خریدار کال خرید',
		hidden: initialHiddenColumnsBullCallSpread.lspBestBuyLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'hspSymbolTitle',
		title: 'کال فروش',
		hidden: initialHiddenColumnsBullCallSpread.hspSymbolTitle,
		tag: 'PanelDetail',
	},
	{
		id: 'hspStrikePrice',
		title: 'قیمت اعمال کال فروش',
		hidden: initialHiddenColumnsBullCallSpread.hspStrikePrice,
		tag: 'PanelDetail',
	},
	{
		id: 'hspBestBuyLimitPrice',
		title: 'بهترین خریدار کال فروش',
		hidden: initialHiddenColumnsBullCallSpread.hspBestBuyLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'hspBestBuyLimitQuantity',
		title: 'حجم خریدار کال فروش',
		hidden: initialHiddenColumnsBullCallSpread.hspBestBuyLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'hspBestSellLimitPrice',
		title: 'بهترین فروشنده کال فروش',
		hidden: initialHiddenColumnsBullCallSpread.hspBestSellLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'hspBestSellLimitQuantity',
		title: 'حجم سرخط فروش کال فروش',
		hidden: initialHiddenColumnsBullCallSpread.hspBestSellLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'lspOpenPositionCount',
		title: 'موقعیت باز کال خرید',
		hidden: initialHiddenColumnsBullCallSpread.lspOpenPositionCount,
		tag: 'PanelDetail',
	},
	{
		id: 'hspOpenPositionCount',
		title: 'موقعیت باز کال فروش',
		hidden: initialHiddenColumnsBullCallSpread.hspOpenPositionCount,
		tag: 'PanelDetail',
	},
	{
		id: 'lspPremiumPercent',
		title: 'قیمت نماد کال خرید',
		hidden: initialHiddenColumnsBullCallSpread.lspPremiumPercent,
		tag: 'PanelDetail',
	},
	{
		id: 'hspPremiumPercent',
		title: 'قیمت نماد کال فروش',
		hidden: initialHiddenColumnsBullCallSpread.hspPremiumPercent,
		tag: 'PanelDetail',
	},
	{
		id: 'bullCallSpreadBEP',
		title: 'سر به سر',
		hidden: initialHiddenColumnsBullCallSpread.bullCallSpreadBEP,
		tag: 'Computational',
	},
	{
		id: 'maxProfitPercent',
		title: 'حداکثر بازده',
		hidden: initialHiddenColumnsBullCallSpread.maxProfitPercent,
		tag: 'Computational',
	},
	{
		id: 'maxLoss',
		title: 'حداکثر زیان',
		hidden: initialHiddenColumnsBullCallSpread.maxLoss,
		tag: 'Computational',
	},
	{
		id: 'inUseCapital',
		title: 'سرمایه درگیر',
		hidden: initialHiddenColumnsBullCallSpread.inUseCapital,
		tag: 'Computational',
	},
	{
		id: 'lspTimeValue',
		title: 'ارزش زمانی کال خرید',
		hidden: initialHiddenColumnsBullCallSpread.lspTimeValue,
		tag: 'Computational',
	},
	{
		id: 'hspTimeValue',
		title: 'ارزش زمانی کال فروش',
		hidden: initialHiddenColumnsBullCallSpread.hspTimeValue,
		tag: 'Computational',
	},
	{
		id: 'lspIntrinsicValue',
		title: 'ارزش ذاتی کال خرید',
		hidden: initialHiddenColumnsBullCallSpread.lspIntrinsicValue,
		tag: 'Computational',
	},
	{
		id: 'hspIntrinsicValue',
		title: 'ارزش ذاتی کال فروش',
		hidden: initialHiddenColumnsBullCallSpread.hspIntrinsicValue,
		tag: 'Computational',
	},
	{
		id: 'lspTradeValue',
		title: 'ارزش معاملات آپشن کال خرید',
		hidden: initialHiddenColumnsBullCallSpread.lspTradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'hspTradeValue',
		title: 'ارزش معاملات آپشن کال فروش',
		hidden: initialHiddenColumnsBullCallSpread.hspTradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeValue',
		title: 'ارزش معاملات سهم پایه',
		hidden: initialHiddenColumnsBullCallSpread.baseTradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeCount',
		title: 'تعداد معاملات پایه',
		hidden: initialHiddenColumnsBullCallSpread.baseTradeCount,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeVolume',
		title: 'حجم معاملات پایه',
		hidden: initialHiddenColumnsBullCallSpread.baseTradeVolume,
		tag: 'PanelDetail',
	},
	{
		id: 'baseLastTradedDate',
		title: 'آخرین معامله پایه',
		hidden: initialHiddenColumnsBullCallSpread.baseLastTradedDate,
		tag: 'PanelDetail',
	},
	{
		id: 'ytm',
		title: 'YTM (بازده موثر)',
		hidden: initialHiddenColumnsBullCallSpread.ytm,
		tag: 'Computational',
	},
];

// ? LongCall
export const initialHiddenColumnsLongCall: Record<TLongCallColumns, boolean> = {
	baseSymbolTitle: false,
	baseTradePriceVarPreviousTradePercent: false,
	dueDays: false,
	symbolTitle: false,
	strikePrice: false,
	openPositionCount: false,
	tradePriceVarPreviousTradePercent: false,
	optionBestSellLimitPrice: false,
	optionBestSellLimitQuantity: false,
	optionBestBuyLimitPrice: true,
	optionBestBuyLimitQuantity: true,
	longCallBEP: false,
	profitPercent: true,
	blackScholes: false,
	timeValue: false,
	intrinsicValue: true,
	profit: true,
	bepDifference: true,
	tradeValue: true,
	baseTradeValue: true,
	baseTradeCount: true,
	baseTradeVolume: true,
	baseLastTradedDate: true,
	actions: false,
};

export const initialColumnsLongCall: Array<IManageColumn<TLongCallColumns>> = [
	{
		id: 'baseSymbolTitle',
		title: 'نماد پایه',
		hidden: initialHiddenColumnsLongCall.baseSymbolTitle,
		tag: 'PanelDetail',
		disabled: true,
	},
	{
		id: 'baseTradePriceVarPreviousTradePercent',
		title: 'قیمت پایه',
		hidden: initialHiddenColumnsLongCall.baseTradePriceVarPreviousTradePercent,
		tag: 'PanelDetail',
	},
	{
		id: 'dueDays',
		title: 'مانده تا سررسید',
		hidden: initialHiddenColumnsLongCall.dueDays,
		tag: 'PanelDetail',
	},
	{
		id: 'symbolTitle',
		title: 'کال',
		hidden: initialHiddenColumnsLongCall.symbolTitle,
		tag: 'PanelDetail',
	},
	{
		id: 'strikePrice',
		title: 'قیمت اعمال',
		hidden: initialHiddenColumnsLongCall.strikePrice,
		tag: 'PanelDetail',
	},
	{
		id: 'openPositionCount',
		title: 'موقعیت باز',
		hidden: initialHiddenColumnsLongCall.openPositionCount,
		tag: 'PanelDetail',
	},
	{
		id: 'tradePriceVarPreviousTradePercent',
		title: 'قیمت نماد آپشن',
		hidden: initialHiddenColumnsLongCall.tradePriceVarPreviousTradePercent,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestBuyLimitPrice',
		title: 'بهترین خریدار',
		hidden: initialHiddenColumnsLongCall.optionBestBuyLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestBuyLimitQuantity',
		title: 'حجم سرخط خرید',
		hidden: initialHiddenColumnsLongCall.optionBestBuyLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestSellLimitPrice',
		title: 'بهترین فروشنده',
		hidden: initialHiddenColumnsLongCall.optionBestSellLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestSellLimitQuantity',
		title: 'حجم سرخط فروش',
		hidden: initialHiddenColumnsLongCall.optionBestSellLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'longCallBEP',
		title: 'سر به سر',
		hidden: initialHiddenColumnsLongCall.longCallBEP,
		tag: 'Computational',
	},
	{
		id: 'profitPercent',
		title: 'حداکثر بازده',
		hidden: initialHiddenColumnsLongCall.profitPercent,
		tag: 'Computational',
		disabled: true,
	},
	{
		id: 'blackScholes',
		title: 'قیمت منصفانه',
		hidden: initialHiddenColumnsLongCall.blackScholes,
		tag: 'Computational',
	},
	{
		id: 'timeValue',
		title: 'ارزش زمانی',
		hidden: initialHiddenColumnsLongCall.timeValue,
		tag: 'Computational',
	},
	{
		id: 'intrinsicValue',
		title: 'ارزش ذاتی',
		hidden: initialHiddenColumnsLongCall.intrinsicValue,
		tag: 'Computational',
	},
	{
		id: 'profit',
		title: 'بازده',
		hidden: initialHiddenColumnsLongCall.profit,
		tag: 'Computational',
		disabled: true,
	},
	{
		id: 'bepDifference',
		title: 'اختلاف تا سر به سر',
		hidden: initialHiddenColumnsLongCall.bepDifference,
		tag: 'Computational',
	},
	{
		id: 'tradeValue',
		title: 'ارزش معاملات آپشن',
		hidden: initialHiddenColumnsLongCall.tradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeValue',
		title: 'ارزش معاملات سهم پایه',
		hidden: initialHiddenColumnsLongCall.baseTradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeCount',
		title: 'تعداد معاملات پایه',
		hidden: initialHiddenColumnsLongCall.baseTradeCount,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeVolume',
		title: 'حجم معاملات پایه',
		hidden: initialHiddenColumnsLongCall.baseTradeVolume,
		tag: 'PanelDetail',
	},
	{
		id: 'baseLastTradedDate',
		title: 'آخرین معامله پایه',
		hidden: initialHiddenColumnsLongCall.baseLastTradedDate,
		tag: 'PanelDetail',
	},
];

// ? LongPut
export const initialHiddenColumnsLongPut: Record<TLongPutColumns, boolean> = {
	baseSymbolTitle: false,
	baseTradePriceVarPreviousTradePercent: false,
	dueDays: false,
	symbolTitle: false,
	strikePrice: false,
	openPositionCount: false,
	tradePriceVarPreviousTradePercent: false,
	optionBestSellLimitPrice: false,
	optionBestSellLimitQuantity: false,
	optionBestLimitPrice: true,
	optionBestLimitVolume: true,
	longPutBEP: false,
	profitPercent: true,
	blackScholes: false,
	timeValue: false,
	intrinsicValue: true,
	profit: true,
	bepDifference: true,
	tradeValue: true,
	baseTradeValue: true,
	baseTradeCount: true,
	baseTradeVolume: true,
	baseLastTradedDate: true,
	actions: false,
};

export const initialColumnsLongPut: Array<IManageColumn<TLongPutColumns>> = [
	{
		id: 'baseSymbolTitle',
		title: 'نماد پایه',
		hidden: initialHiddenColumnsLongPut.baseSymbolTitle,
		disabled: true,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradePriceVarPreviousTradePercent',
		title: 'قیمت پایه',
		hidden: initialHiddenColumnsLongPut.baseTradePriceVarPreviousTradePercent,
		tag: 'PanelDetail',
	},
	{
		id: 'dueDays',
		title: 'مانده تا سررسید',
		hidden: initialHiddenColumnsLongPut.dueDays,
		tag: 'PanelDetail',
	},
	{
		id: 'symbolTitle',
		title: 'کال',
		hidden: initialHiddenColumnsLongPut.symbolTitle,
		tag: 'PanelDetail',
	},
	{
		id: 'strikePrice',
		title: 'قیمت اعمال',
		hidden: initialHiddenColumnsLongPut.strikePrice,
		tag: 'PanelDetail',
	},
	{
		id: 'openPositionCount',
		title: 'موقعیت باز',
		hidden: initialHiddenColumnsLongPut.openPositionCount,
		tag: 'PanelDetail',
	},
	{
		id: 'tradePriceVarPreviousTradePercent',
		title: 'قیمت نماد آپشن',
		hidden: initialHiddenColumnsLongPut.tradePriceVarPreviousTradePercent,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestLimitPrice',
		title: 'بهترین خریدار',
		hidden: initialHiddenColumnsLongPut.optionBestLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestLimitVolume',
		title: 'حجم سرخط خرید',
		hidden: initialHiddenColumnsLongPut.optionBestLimitVolume,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestSellLimitPrice',
		title: 'بهترین فروشنده',
		hidden: initialHiddenColumnsLongPut.optionBestSellLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestSellLimitQuantity',
		title: 'حجم سرخط فروش',
		hidden: initialHiddenColumnsLongPut.optionBestSellLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'longPutBEP',
		title: 'سر به سر',
		hidden: initialHiddenColumnsLongPut.longPutBEP,
		tag: 'Computational',
	},
	{
		id: 'profitPercent',
		title: 'حداکثر بازده',
		hidden: initialHiddenColumnsLongPut.profitPercent,
		tag: 'Computational',
		disabled: true,
	},
	{
		id: 'blackScholes',
		title: 'قیمت منصفانه',
		hidden: initialHiddenColumnsLongPut.blackScholes,
		tag: 'Computational',
	},
	{
		id: 'timeValue',
		title: 'ارزش زمانی',
		hidden: initialHiddenColumnsLongPut.timeValue,
		tag: 'Computational',
	},
	{
		id: 'intrinsicValue',
		title: 'ارزش ذاتی',
		hidden: initialHiddenColumnsLongPut.intrinsicValue,
		tag: 'Computational',
	},
	{
		id: 'profit',
		title: 'بازده',
		hidden: initialHiddenColumnsLongPut.profit,
		tag: 'Computational',
		disabled: true,
	},
	{
		id: 'bepDifference',
		title: 'اختلاف تا سر به سر',
		hidden: initialHiddenColumnsLongPut.bepDifference,
		tag: 'Computational',
	},
	{
		id: 'tradeValue',
		title: 'ارزش معاملات آپشن',
		hidden: initialHiddenColumnsLongPut.tradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeValue',
		title: 'ارزش معاملات سهم پایه',
		hidden: initialHiddenColumnsLongPut.baseTradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeCount',
		title: 'تعداد معاملات پایه',
		hidden: initialHiddenColumnsLongPut.baseTradeCount,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeVolume',
		title: 'حجم معاملات پایه',
		hidden: initialHiddenColumnsLongPut.baseTradeVolume,
		tag: 'PanelDetail',
	},
	{
		id: 'baseLastTradedDate',
		title: 'آخرین معامله پایه',
		hidden: initialHiddenColumnsLongPut.baseLastTradedDate,
		tag: 'PanelDetail',
	},
];

// ? Conversion
export const initialHiddenColumnsConversion: Record<TConversionColumns, boolean> = {
	baseSymbolTitle: false,
	baseTradePriceVarPreviousTradePercent: false,
	dueDays: false,
	strikePrice: false,
	callPremiumPercent: true,
	putPremiumPercent: true,
	callSymbolTitle: false,
	callBestBuyLimitPrice: false,
	callBestBuyLimitQuantity: false,
	callOpenPositionCount: true,
	callBestSellLimitPrice: true,
	callBestSellLimitQuantity: true,
	putSymbolTitle: false,
	putBestSellLimitPrice: false,
	putBestSellLimitQuantity: false,
	putOpenPositionCount: true,
	putBestBuyLimitPrice: true,
	putBestBuyLimitQuantity: true,
	profit: false,
	inUseCapital: false,
	ytm: true,
	callTradeValue: true,
	putTradeValue: true,
	baseTradeValue: true,
	baseTradeCount: true,
	baseTradeVolume: true,
	baseLastTradedDate: true,
	actions: false,
};

export const initialColumnsConversion: Array<IManageColumn<TConversionColumns>> = [
	{
		id: 'baseSymbolTitle',
		title: 'نماد پایه',
		hidden: initialHiddenColumnsConversion.baseSymbolTitle,
		tag: 'PanelDetail',
		disabled: true,
	},
	{
		id: 'baseTradePriceVarPreviousTradePercent',
		title: 'قیمت پایه',
		hidden: initialHiddenColumnsConversion.baseTradePriceVarPreviousTradePercent,
		tag: 'PanelDetail',
	},
	{
		id: 'dueDays',
		title: 'مانده تا سررسید',
		hidden: initialHiddenColumnsConversion.dueDays,
		tag: 'PanelDetail',
	},
	{
		id: 'strikePrice',
		title: 'قیمت اعمال',
		hidden: initialHiddenColumnsConversion.strikePrice,
		tag: 'PanelDetail',
	},
	{
		id: 'callPremiumPercent',
		title: 'قیمت نماد کال',
		hidden: initialHiddenColumnsConversion.callPremiumPercent,
		tag: 'PanelDetail',
	},
	{
		id: 'putPremiumPercent',
		title: 'قیمت نماد پوت',
		hidden: initialHiddenColumnsConversion.putPremiumPercent,
		tag: 'PanelDetail',
	},
	{
		id: 'callSymbolTitle',
		title: 'کال',
		hidden: initialHiddenColumnsConversion.callSymbolTitle,
		tag: 'PanelDetail',
	},
	{
		id: 'callBestBuyLimitPrice',
		title: 'بهترین خریدار کال',
		hidden: initialHiddenColumnsConversion.callBestBuyLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'callBestBuyLimitQuantity',
		title: 'حجم سرخط خرید کال',
		hidden: initialHiddenColumnsConversion.callBestBuyLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'callOpenPositionCount',
		title: 'موقعیت باز کال',
		hidden: initialHiddenColumnsConversion.callOpenPositionCount,
		tag: 'PanelDetail',
	},
	{
		id: 'callBestSellLimitPrice',
		title: 'بهترین فروشنده کال',
		hidden: initialHiddenColumnsConversion.callBestSellLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'callBestSellLimitQuantity',
		title: 'حجم سرخط فروش کال',
		hidden: initialHiddenColumnsConversion.callBestSellLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'putSymbolTitle',
		title: 'پوت',
		hidden: initialHiddenColumnsConversion.putSymbolTitle,
		tag: 'PanelDetail',
	},
	{
		id: 'putBestSellLimitPrice',
		title: 'بهترین فروشنده پوت',
		hidden: initialHiddenColumnsConversion.putBestSellLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'putBestSellLimitQuantity',
		title: 'حجم سرخط فروش پوت',
		hidden: initialHiddenColumnsConversion.putBestSellLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'putOpenPositionCount',
		title: 'موقعیت باز پوت',
		hidden: initialHiddenColumnsConversion.putOpenPositionCount,
		tag: 'PanelDetail',
	},
	{
		id: 'putBestBuyLimitPrice',
		title: 'بهترین خریدار پوت',
		hidden: initialHiddenColumnsConversion.putBestBuyLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'putBestBuyLimitQuantity',
		title: 'حجم سرخط خرید پوت',
		hidden: initialHiddenColumnsConversion.putBestBuyLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'profit',
		title: 'بازده',
		hidden: initialHiddenColumnsConversion.profit,
		tag: 'Computational',
	},
	{
		id: 'inUseCapital',
		title: 'سرمایه درگیر',
		hidden: initialHiddenColumnsConversion.inUseCapital,
		tag: 'Computational',
	},
	{
		id: 'ytm',
		title: 'YTM (بازده موثر)',
		hidden: initialHiddenColumnsConversion.ytm,
		tag: 'Computational',
	},
	{
		id: 'callTradeValue',
		title: 'ارزش معاملات کال',
		hidden: initialHiddenColumnsConversion.callTradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'putTradeValue',
		title: 'ارزش معاملات پوت',
		hidden: initialHiddenColumnsConversion.putTradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeValue',
		title: 'ارزش معاملات سهم پایه',
		hidden: initialHiddenColumnsConversion.baseTradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeCount',
		title: 'تعداد معاملات پایه',
		hidden: initialHiddenColumnsConversion.baseTradeCount,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeVolume',
		title: 'حجم معاملات پایه',
		hidden: initialHiddenColumnsConversion.baseTradeVolume,
		tag: 'PanelDetail',
	},
	{
		id: 'baseLastTradedDate',
		title: 'آخرین معامله پایه',
		hidden: initialHiddenColumnsConversion.baseLastTradedDate,
		tag: 'PanelDetail',
	},
];

// ? LongStraddle
export const initialHiddenColumnsLongStraddle: Record<TLongStraddleColumns, boolean> = {
	baseSymbolTitle: false,
	baseTradePriceVarPreviousTradePercent: false,
	dueDays: false,
	strikePrice: false,
	callSymbolTitle: false,
	callBestSellLimitPrice: false,
	callBestSellLimitQuantity: false,
	putSymbolTitle: false,
	putBestSellLimitPrice: false,
	putBestSellLimitQuantity: false,
	callOpenPositionCount: true,
	putOpenPositionCount: true,
	callPremiumPercent: true,
	putPremiumPercent: true,
	highBEP: false,
	lowBEP: false,
	maxLoss: false,
	inUseCapital: true,
	callTimeValue: true,
	putTimeValue: true,
	callIntrinsicValue: true,
	putIntrinsicValue: true,
	callBestBuyLimitPrice: true,
	callBestBuyLimitQuantity: true,
	putBestBuyLimitPrice: true,
	putBestBuyLimitQuantity: true,
	callTradeValue: true,
	putTradeValue: true,
	baseTradeValue: true,
	baseTradeCount: true,
	baseTradeVolume: true,
	baseLastTradedDate: true,
	actions: false,
};

export const initialColumnsLongStraddle: Array<IManageColumn<TLongStraddleColumns>> = [
	{
		id: 'baseSymbolTitle',
		title: 'نماد پایه',
		hidden: initialHiddenColumnsLongStraddle.baseSymbolTitle,
		tag: 'PanelDetail',
		disabled: true,
	},
	{
		id: 'baseTradePriceVarPreviousTradePercent',
		title: 'قیمت پایه',
		hidden: initialHiddenColumnsLongStraddle.baseTradePriceVarPreviousTradePercent,
		tag: 'PanelDetail',
	},
	{
		id: 'dueDays',
		title: 'مانده تا سررسید',
		hidden: initialHiddenColumnsLongStraddle.dueDays,
		tag: 'PanelDetail',
	},
	{
		id: 'strikePrice',
		title: 'قیمت اعمال',
		hidden: initialHiddenColumnsLongStraddle.strikePrice,
		tag: 'PanelDetail',
	},
	{
		id: 'callSymbolTitle',
		title: 'کال',
		hidden: initialHiddenColumnsLongStraddle.callSymbolTitle,
		tag: 'PanelDetail',
	},
	{
		id: 'callBestSellLimitPrice',
		title: 'قیمت فروشنده کال',
		hidden: initialHiddenColumnsLongStraddle.callBestSellLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'callBestSellLimitQuantity',
		title: 'حجم فروشنده کال',
		hidden: initialHiddenColumnsLongStraddle.callBestSellLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'putSymbolTitle',
		title: 'پوت',
		hidden: initialHiddenColumnsLongStraddle.putSymbolTitle,
		tag: 'PanelDetail',
	},
	{
		id: 'putBestSellLimitPrice',
		title: 'قیمت فروشنده پوت',
		hidden: initialHiddenColumnsLongStraddle.putBestSellLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'putBestSellLimitQuantity',
		title: 'حجم فروشنده پوت',
		hidden: initialHiddenColumnsLongStraddle.putBestSellLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'callOpenPositionCount',
		title: 'موقعیت باز کال',
		hidden: initialHiddenColumnsLongStraddle.callOpenPositionCount,
		tag: 'PanelDetail',
	},
	{
		id: 'putOpenPositionCount',
		title: 'موقعیت باز پوت',
		hidden: initialHiddenColumnsLongStraddle.putOpenPositionCount,
		tag: 'PanelDetail',
	},
	{
		id: 'callPremiumPercent',
		title: 'قیمت نماد کال',
		hidden: initialHiddenColumnsLongStraddle.callPremiumPercent,
		tag: 'PanelDetail',
	},
	{
		id: 'putPremiumPercent',
		title: 'قیمت نماد پوت',
		hidden: initialHiddenColumnsLongStraddle.putPremiumPercent,
		tag: 'PanelDetail',
	},
	{
		id: 'highBEP',
		title: 'سر به سر بالا',
		hidden: initialHiddenColumnsLongStraddle.highBEP,
		tag: 'Computational',
	},
	{
		id: 'lowBEP',
		title: 'سر به سر پایین',
		hidden: initialHiddenColumnsLongStraddle.lowBEP,
		tag: 'Computational',
	},
	{
		id: 'maxLoss',
		title: 'حداکثر زیان زیان',
		hidden: initialHiddenColumnsLongStraddle.maxLoss,
		tag: 'Computational',
	},
	{
		id: 'inUseCapital',
		title: 'سرمایه درگیر',
		hidden: initialHiddenColumnsLongStraddle.inUseCapital,
		tag: 'Computational',
	},
	{
		id: 'callTimeValue',
		title: 'ارزش زمانی کال',
		hidden: initialHiddenColumnsLongStraddle.callTimeValue,
		tag: 'Computational',
	},
	{
		id: 'putTimeValue',
		title: 'ارزش زمانی پوت',
		hidden: initialHiddenColumnsLongStraddle.putTimeValue,
		tag: 'Computational',
	},
	{
		id: 'callIntrinsicValue',
		title: 'ارزش ذاتی کال',
		hidden: initialHiddenColumnsLongStraddle.callIntrinsicValue,
		tag: 'Computational',
	},
	{
		id: 'putIntrinsicValue',
		title: 'ارزش ذاتی پوت',
		hidden: initialHiddenColumnsLongStraddle.putIntrinsicValue,
		tag: 'Computational',
	},
	{
		id: 'callBestBuyLimitPrice',
		title: 'بهترین خریدار کال',
		hidden: initialHiddenColumnsLongStraddle.callBestBuyLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'callBestBuyLimitQuantity',
		title: 'حجم سرخط خرید کال',
		hidden: initialHiddenColumnsLongStraddle.callBestBuyLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'putBestBuyLimitPrice',
		title: 'بهترین خریدار پوت',
		hidden: initialHiddenColumnsLongStraddle.putBestBuyLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'putBestBuyLimitQuantity',
		title: 'حجم سرخط خرید پوت',
		hidden: initialHiddenColumnsLongStraddle.putBestBuyLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'callTradeValue',
		title: 'ارزش معاملات کال',
		hidden: initialHiddenColumnsLongStraddle.callTradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'putTradeValue',
		title: 'ارزش معاملات پوت',
		hidden: initialHiddenColumnsLongStraddle.putTradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeValue',
		title: 'ارزش معاملات سهم پایه',
		hidden: initialHiddenColumnsLongStraddle.baseTradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeCount',
		title: 'تعداد معاملات پایه',
		hidden: initialHiddenColumnsLongStraddle.baseTradeCount,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeVolume',
		title: 'حجم معاملات پایه',
		hidden: initialHiddenColumnsLongStraddle.baseTradeVolume,
		tag: 'PanelDetail',
	},
	{
		id: 'baseLastTradedDate',
		title: 'آخرین معامله پایه',
		hidden: initialHiddenColumnsLongStraddle.baseLastTradedDate,
		tag: 'PanelDetail',
	},
];

// ? ProtectivePut
export const initialHiddenColumnsProtectivePut: Record<TProtectivePutColumns, boolean> = {
	baseSymbolTitle: false,
	baseTradePriceVarPreviousTradePercent: false,
	dueDays: false,
	symbolTitle: false,
	strikePrice: false,
	openPositionCount: false,
	tradePriceVarPreviousTradePercent: true,
	optionBestSellLimitPrice: false,
	optionBestSellLimitQuantity: false,
	optionBestBuyLimitPrice: true,
	optionBestBuyLimitQuantity: true,
	protectivePutBEP: false,
	maxLossPercent: false,
	profit: true,
	profitPercent: false,
	inUseCapital: false,
	blackScholes: true,
	timeValue: true,
	intrinsicValue: true,
	bepDifference: true,
	tradeValue: true,
	baseTradeValue: true,
	baseTradeCount: true,
	baseTradeVolume: true,
	baseLastTradedDate: true,
	actions: false,
};

export const initialColumnsProtectivePut: Array<IManageColumn<TProtectivePutColumns>> = [
	{
		id: 'baseSymbolTitle',
		title: 'نماد پایه',
		hidden: false,
		tag: 'PanelDetail',
		disabled: true,
	},
	{
		id: 'baseTradePriceVarPreviousTradePercent',
		title: 'قیمت پایه',
		hidden: false,
		tag: 'PanelDetail',
	},
	{
		id: 'dueDays',
		title: 'مانده تا سررسید',
		hidden: false,
		tag: 'PanelDetail',
	},
	{
		id: 'symbolTitle',
		title: 'اختیار فروش',
		hidden: false,
		tag: 'PanelDetail',
	},
	{
		id: 'strikePrice',
		title: 'قیمت اعمال',
		hidden: false,
		tag: 'PanelDetail',
	},
	{
		id: 'openPositionCount',
		title: 'موقعیت باز',
		hidden: false,
		tag: 'PanelDetail',
	},
	{
		id: 'tradePriceVarPreviousTradePercent',
		title: 'قیمت نماد آپشن',
		hidden: false,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestSellLimitPrice',
		title: 'بهترین فروشنده',
		hidden: false,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestSellLimitQuantity',
		title: 'حجم سرخط فروش',
		hidden: false,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestBuyLimitPrice',
		title: 'بهترین خریدار',
		hidden: false,
		tag: 'PanelDetail',
	},
	{
		id: 'optionBestBuyLimitQuantity',
		title: 'حجم سرخط خرید',
		hidden: false,
		tag: 'PanelDetail',
	},
	{
		id: 'protectivePutBEP',
		title: 'سر به سر',
		hidden: false,
		tag: 'Computational',
	},
	{
		id: 'maxLossPercent',
		title: 'حداکثر زیان',
		hidden: false,
		tag: 'Computational',
	},
	{
		id: 'profit',
		title: 'بازده',
		hidden: false,
		tag: 'Computational',
		disabled: true,
	},
	{
		id: 'profitPercent',
		title: 'حداکثر بازده',
		hidden: false,
		tag: 'Computational',
		disabled: true,
	},
	{
		id: 'inUseCapital',
		title: 'سرمایه درگیر',
		hidden: false,
		tag: 'Computational',
	},
	{
		id: 'blackScholes',
		title: 'قیمت منصفانه',
		hidden: false,
		tag: 'Computational',
	},
	{
		id: 'timeValue',
		title: 'ارزش زمانی',
		hidden: false,
		tag: 'Computational',
	},
	{
		id: 'intrinsicValue',
		title: 'ارزش ذاتی',
		hidden: false,
		tag: 'Computational',
	},
	{
		id: 'bepDifference',
		title: 'اختلاف تا سر به سر',
		hidden: false,
		tag: 'Computational',
	},
	{
		id: 'tradeValue',
		title: 'ارزش معاملات آپشن',
		hidden: false,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeValue',
		title: 'ارزش معاملات سهم پایه',
		hidden: false,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeCount',
		title: 'تعداد معاملات پایه',
		hidden: false,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeVolume',
		title: 'حجم معاملات پایه',
		hidden: false,
		tag: 'PanelDetail',
	},
	{
		id: 'baseLastTradedDate',
		title: 'آخرین معامله پایه',
		hidden: false,
		tag: 'PanelDetail',
	},
];

// ? BearPutSpread
export const initialHiddenColumnsBearPutSpread: Record<TBearPutSpreadColumns, boolean> = {
	baseSymbolTitle: false,
	baseTradePriceVarPreviousTradePercent: false,
	dueDays: false,
	hspSymbolTitle: false,
	hspStrikePrice: true,
	hspBestSellLimitPrice: false,
	hspBestSellLimitQuantity: false,
	hspBestBuyLimitPrice: true,
	hspBestBuyLimitQuantity: true,
	lspSymbolTitle: false,
	lspStrikePrice: false,
	lspBestBuyLimitPrice: false,
	lspBestBuyLimitQuantity: false,
	lspBestSellLimitPrice: true,
	lspBestSellLimitQuantity: true,
	hspOpenPositionCount: true,
	lspOpenPositionCount: true,
	hspPremiumPercent: true,
	lspPremiumPercent: true,
	bullCallSpreadBEP: false,
	maxProfitPercent: false,
	maxLoss: false,
	inUseCapital: true,
	lspTimeValue: true,
	hspTimeValue: true,
	hspIntrinsicValue: true,
	lspIntrinsicValue: true,
	hspTradeValue: true,
	lspTradeValue: true,
	baseTradeValue: true,
	baseTradeCount: true,
	baseTradeVolume: true,
	baseLastTradedDate: true,
	ytm: true,
	actions: false,
};

export const initialColumnsBearPutSpread: Array<IManageColumn<TBearPutSpreadColumns>> = [
	{
		id: 'baseSymbolTitle',
		title: 'نماد پایه',
		hidden: initialHiddenColumnsBearPutSpread.baseSymbolTitle,
		tag: 'PanelDetail',
		disabled: true,
	},
	{
		id: 'baseTradePriceVarPreviousTradePercent',
		title: 'قیمت پایه',
		hidden: initialHiddenColumnsBearPutSpread.baseTradePriceVarPreviousTradePercent,
		tag: 'PanelDetail',
	},
	{
		id: 'dueDays',
		title: 'مانده تا سررسید',
		hidden: initialHiddenColumnsBearPutSpread.dueDays,
		tag: 'PanelDetail',
	},
	{
		id: 'hspSymbolTitle',
		title: 'پوت خرید',
		hidden: initialHiddenColumnsBearPutSpread.hspSymbolTitle,
		tag: 'PanelDetail',
	},
	{
		id: 'hspStrikePrice',
		title: 'قیمت اعمال پوت خرید',
		hidden: initialHiddenColumnsBearPutSpread.hspStrikePrice,
		tag: 'PanelDetail',
	},
	{
		id: 'hspBestSellLimitPrice',
		title: 'قیمت فروشنده پوت خرید',
		hidden: initialHiddenColumnsBearPutSpread.hspBestSellLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'hspBestSellLimitQuantity',
		title: 'حجم فروشنده پوت خرید',
		hidden: initialHiddenColumnsBearPutSpread.hspBestSellLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'hspBestBuyLimitPrice',
		title: 'قیمت خریدار پوت خرید',
		hidden: initialHiddenColumnsBearPutSpread.hspBestBuyLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'hspBestBuyLimitQuantity',
		title: 'حجم خریدار پوت خرید',
		hidden: initialHiddenColumnsBearPutSpread.hspBestBuyLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'lspSymbolTitle',
		title: 'پوت فروش',
		hidden: initialHiddenColumnsBearPutSpread.lspSymbolTitle,
		tag: 'PanelDetail',
	},
	{
		id: 'lspStrikePrice',
		title: 'قیمت اعمال پوت فروش',
		hidden: initialHiddenColumnsBearPutSpread.lspStrikePrice,
		tag: 'PanelDetail',
	},
	{
		id: 'lspBestBuyLimitPrice',
		title: 'قیمت خریدار پوت فروش',
		hidden: initialHiddenColumnsBearPutSpread.lspBestBuyLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'lspBestBuyLimitQuantity',
		title: 'حجم خریدار پوت فروش',
		hidden: initialHiddenColumnsBearPutSpread.lspBestBuyLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'lspBestSellLimitPrice',
		title: 'بهترین فروشنده پوت فروش',
		hidden: initialHiddenColumnsBearPutSpread.lspBestSellLimitPrice,
		tag: 'PanelDetail',
	},
	{
		id: 'lspBestSellLimitQuantity',
		title: 'حجم فروشنده پوت فروش',
		hidden: initialHiddenColumnsBearPutSpread.lspBestSellLimitQuantity,
		tag: 'PanelDetail',
	},
	{
		id: 'hspOpenPositionCount',
		title: 'موقعیت باز پوت خرید',
		hidden: initialHiddenColumnsBearPutSpread.hspOpenPositionCount,
		tag: 'PanelDetail',
	},
	{
		id: 'lspOpenPositionCount',
		title: 'موقعیت باز پوت فروش',
		hidden: initialHiddenColumnsBearPutSpread.lspOpenPositionCount,
		tag: 'PanelDetail',
	},
	{
		id: 'hspPremiumPercent',
		title: 'قیمت نماد پوت خرید',
		hidden: initialHiddenColumnsBearPutSpread.hspPremiumPercent,
		tag: 'PanelDetail',
	},
	{
		id: 'lspPremiumPercent',
		title: 'قیمت نماد پوت فروش',
		hidden: initialHiddenColumnsBearPutSpread.lspPremiumPercent,
		tag: 'PanelDetail',
	},
	{
		id: 'bullCallSpreadBEP',
		title: 'سر به سر',
		hidden: initialHiddenColumnsBearPutSpread.bullCallSpreadBEP,
		tag: 'Computational',
	},
	{
		id: 'maxProfitPercent',
		title: 'حداکثر بازده',
		hidden: initialHiddenColumnsBearPutSpread.maxProfitPercent,
		tag: 'Computational',
	},
	{
		id: 'maxLoss',
		title: 'حداکثر زیان',
		hidden: initialHiddenColumnsBearPutSpread.maxLoss,
		tag: 'Computational',
	},
	{
		id: 'inUseCapital',
		title: 'سرمایه درگیر',
		hidden: initialHiddenColumnsBearPutSpread.inUseCapital,
		tag: 'Computational',
	},
	{
		id: 'lspTimeValue',
		title: 'ارزش زمانی پوت خرید',
		hidden: initialHiddenColumnsBearPutSpread.lspTimeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'hspTimeValue',
		title: 'ارزش زمانی پوت فروش',
		hidden: initialHiddenColumnsBearPutSpread.hspTimeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'hspIntrinsicValue',
		title: 'ارزش ذاتی پوت خرید',
		hidden: initialHiddenColumnsBearPutSpread.hspIntrinsicValue,
		tag: 'PanelDetail',
	},
	{
		id: 'lspIntrinsicValue',
		title: 'ارزش ذاتی پوت فروش',
		hidden: initialHiddenColumnsBearPutSpread.lspIntrinsicValue,
		tag: 'PanelDetail',
	},
	{
		id: 'hspTradeValue',
		title: 'ارزش معاملات آپشن پوت خرید',
		hidden: initialHiddenColumnsBearPutSpread.hspTradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'lspTradeValue',
		title: 'ارزش معاملات آپشن پوت فروش',
		hidden: initialHiddenColumnsBearPutSpread.lspTradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeValue',
		title: 'ارزش معاملات سهم پایه',
		hidden: initialHiddenColumnsBearPutSpread.baseTradeValue,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeCount',
		title: 'تعداد معاملات پایه',
		hidden: initialHiddenColumnsBearPutSpread.baseTradeCount,
		tag: 'PanelDetail',
	},
	{
		id: 'baseTradeVolume',
		title: 'حجم معاملات پایه',
		hidden: initialHiddenColumnsBearPutSpread.baseTradeVolume,
		tag: 'PanelDetail',
	},
	{
		id: 'baseLastTradedDate',
		title: 'آخرین معامله پایه',
		hidden: initialHiddenColumnsBearPutSpread.baseLastTradedDate,
		tag: 'PanelDetail',
	},
	{
		id: 'ytm',
		title: 'YTM (بازده موثر)',
		hidden: initialHiddenColumnsBearPutSpread.ytm,
		tag: 'Computational',
	},
	{
		id: 'actions',
		title: 'عملیات',
		hidden: initialHiddenColumnsBearPutSpread.actions,
		tag: 'None',
		disabled: true,
	},
];
